FROM node:18-alpine

WORKDIR /app

COPY package*.json ./
COPY angular.json tsconfig*.json proxy.conf.json ./

RUN npm ci

EXPOSE 4200

CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "500"]
